---

- name: configure rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  when: rabbitmq_config is defined
  notify:
    - rabbitmq restart

- include: node_start.yml

- include: vhosts.yml

- include: users.yml

- include: plugins.yml
